create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null,
  source text,
  created_at timestamptz not null default now(),
  constraint waitlist_email_length check (char_length(email) < 320)
);

alter table public.waitlist enable row level security;

revoke all on public.waitlist from anon;
revoke all on public.waitlist from authenticated;

grant usage on schema public to anon;
grant insert on table public.waitlist to anon;

drop policy if exists waitlist_insert on public.waitlist;
create policy waitlist_insert
on public.waitlist
for insert
to anon
with check (
  email is not null
  and char_length(email) < 320
);
